name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        working-directory: ${{github.workspace}}
        run: git submodule update --init --recursive
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y libboost-dev ccache ninja-build      
      - name: Configure XAD
        working-directory: ${{github.workspace}}/repos/XAD
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DXAD_SIMD_OPTION='SSE'
      - name: Build XAD
        working-directory: ${{github.workspace}}/repos/XAD/build
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install    
      - name: Configure CMake QL
        working-directory: ${{github.workspace}}/repos/QuantLib
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_TAGGED_LAYOUT=OFF -DBOOST_ROOT=/usr
      - name: Build QL
        working-directory: ${{github.workspace}}/repos/QuantLib/build
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install  
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build    
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target INSTALL
      - name: Test
        working-directory: ${{github.workspace}}/build/test
        run: ctest -C ${{env.BUILD_TYPE}}
