name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  get_repos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Repos
        uses: actions/cache@v2
        with:
          path: repos
          key: repos

  build_boost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Boost
        run: sudo apt-get -y update && sudo apt-get -y install libboost-dev
      - name: Cache Boost
        uses: actions/cache@v2
        with:
          path: /usr/include/boost
          key: boost-cache
          
  build_XAD:
    runs-on: ubuntu-latest
    needs: get_repos
    steps:
      - uses: actions/checkout@v2
      - name: Configure XAD
        run: mkdir -p repos/XAD/build && cd repos/XAD/build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DXAD_SIMD_OPTION='SSE' 
      - name: Build XAD
        run: cd repos/XAD/build && cmake --build . --config ${{env.BUILD_TYPE}}      
      - name: Cache XAD
        uses: actions/cache@v2
        with:
          path: repos/XAD/build
          key: xad-cache
    
  build_ql:
    runs-on: ubuntu-latest
    needs: [get_repos, build_boost]
    steps:
      - uses: actions/checkout@v2
      - name: Boost
        run: sudo apt-get -y update && sudo apt-get -y install libboost-dev
      - name: Configure CMake QL
        run: mkdir -p repos/QuantLib/build && cd repos/QuantLib/build && cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_TAGGED_LAYOUT=OFF
      - name: Build QL
        run: cd repos/QuantLib/build && cmake --build . --config ${{env.BUILD_TYPE}}
      - name: Cache QL
        uses: actions/cache@v2
        with:
          path: repos/QuantLib/build
          key: ql-cache
    
  build_atlas:
    runs-on: ubuntu-latest
    needs: [get_repos, build_boost, build_ql, build_XAD]
    steps:
      - uses: actions/checkout@v2          
      - name: Configure CMake
        run: mkdir -p build && cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build    
        run: cmake --build build --config ${{env.BUILD_TYPE}}
      - name: Test
        working-directory: build/test
        run: ctest -C ${{env.BUILD_TYPE}}
