name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  INSTALL_DIR: install

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout submodules
        working-directory: ${{github.workspace}}
        run: git submodule update --init --recursive
      - name: Setup
        run: |
          sudo apt update
          sudo apt install -y libboost-dev ccache ninja-build
          sudo apt install -y python3 python3-pip
          pip3 install setuptools wheel twine pybind11 cibuildwheel
      - name: Configure pybind11
        working-directory: ${{github.workspace}}/repos/pybind11
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/${{env.INSTALL_DIR}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/${{env.INSTALL_DIR}} -DBUILD_TESTING=OFF
      - name: Build pybind11
        working-directory: ${{github.workspace}}/repos/pybind11/build
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install    
      - name: Configure XAD
        working-directory: ${{github.workspace}}/repos/XAD
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DXAD_SIMD_OPTION='SSE'  -DXAD_ENABLE_TESTS=OFF -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/${{env.INSTALL_DIR}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/${{env.INSTALL_DIR}}
      - name: Build XAD
        working-directory: ${{github.workspace}}/repos/XAD/build
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install    
      - name: Configure QL
        working-directory: ${{github.workspace}}/repos/QuantLib
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DQL_BUILD_BENCHMARK=OFF -DQL_BUILD_EXAMPLES=OFF -DQL_BUILD_TEST_SUITE=OFF -DQL_TAGGED_LAYOUT=OFF -DBOOST_ROOT=/usr -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/${{env.INSTALL_DIR}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/${{env.INSTALL_DIR}}
      - name: Build QL
        working-directory: ${{github.workspace}}/repos/QuantLib/build
        run: cmake --build . --config ${{env.BUILD_TYPE}} --target install  
      - name: Configure Atlas
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/${{env.INSTALL_DIR}} -DCMAKE_PREFIX_PATH=${{github.workspace}}/${{env.INSTALL_DIR}} -DBUILD_BENCHMARK=OFF -DBUILD_EXAMPLES=OFF
      - name: Build Atlas
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target install
      - name: Test
        working-directory: ${{github.workspace}}/build/test
        run: ctest -C ${{env.BUILD_TYPE}}
      
      - name: Build and upload Python package
        working-directory: ${{github.workspace}}/python
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse  
          python3 -m twine upload --skip-existing wheelhouse/* -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }}      
        env:          
          CIBW_ENVIRONMENT_PASS_LINUX: LD_LIBRARY_PATH LIBRARY_PATH PATH


